### ISSUE TITLE
Not waiting for router transitions

### ISSUE THREAD

**Issue by simonihmig** [emberjs/ember-test-helpers#411]
### Problem

`settled()` and all other async test helpers that use it do not wait for a model hook implemented using native async/await. 

### Test scenario:

In an application test there is an `await click()`, which triggers a route transition. The model hook is implemented using native async/await. The test continues to run beyond the await, even before the model hook has resolved (which means the new route hasn't rendered yet, though the test expects that)

### Solution

As suggested by @rwjblue on Discord: wait for active router transitions, as is the case in old `ember-testing`: https://github.com/emberjs/ember.js/blob/615daa2eeef971e578de75e6319baca3b0ec0508/packages/ember-testing/lib/helpers/wait.js#L45-L49

### Reproduction

https://github.com/simonihmig/async-model-reproduction

First test uses an explicit delay and passes. Second just `await`s `click()` and fails: https://github.com/simonihmig/async-model-reproduction/blob/master/tests/acceptance/foo-test.js

**Comment by rwjblue** [comment]
Thank you for reporting! I can't believe I missed this in the initial development 😢 .

**Comment by simonihmig** [comment]
@rwjblue getting totally confused now. I just pushed another commit to the repo, with a bar route that returns an RSVP promise. And even that is not working!? So seems not even related to native Promises/async!?? 

I mean this *has always been working*, I am getting totally lost now... 🤔

Anything that has changed, that would explain this?

**Comment by dexturr** [comment]
I have run into this issue as well when trying to upgrade a project. 

I think this is an issue in ember-source as on my project if I only change ember-source from 3.1.1 -> 3.2.0 this issue appears with the same version of ember-test-helpers and every other dependency.

**Comment by rwjblue** [comment]
Yep, this issue will be closed when the issue is fixed. 😸

**Comment by rwjblue** [comment]
Fixed in https://github.com/emberjs/ember-test-helpers/pull/482, released in @ember/test-helpers@1.2.1.

**Comment by lolmaus** [comment]
I'm on `@ember/test-helpers` 1.3.2 and transitions are still not being waited for.

E. g. I have this with [ember-router-helpers](https://github.com/rwjblue/ember-router-helpers/):

    <button {{action (transition-to "foo")}}>

When I do `await click('button')` in tests, it doesn't wait for the transition to finish.

I had to fork the `transition-to` helper and wrap it with a custom `@waitForPromise` decorator which registers a test waiter based on returned promise resolution.

Likewise, `this.transitionToRoute('foo')` in controller crashes tests unless I use it with my `@waitForPromise` decorator.

* `ember-source`: 3.9.0-canary+7df81ec4
* `ember-cli`: 3.8.0-beta.1+c94b9978
* `@ember/test-helpers`: 1.3.2

Please help me figure this out.

PS Not sure if it's relevant but the problem does not occur when I filter the list of tests so that a problematic test is the only one running -- in that case it passes.

**Comment by rwjblue** [comment]
Would need a reproduction to be able to do anything useful. Feel free to open a new issue once you have a repro...
